# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 57) do

  create_table "directories", :force => true do |t|
    t.datetime "modified"
    t.integer  "parent_id"
    t.integer  "lft"
    t.integer  "rgt"
    t.string   "name",                                           :null => false
    t.integer  "server_id",                                      :null => false
    t.integer  "level",                                          :null => false
    t.string   "path",        :limit => 8192,                    :null => false
    t.integer  "bytes",                       :default => 0,     :null => false
    t.integer  "blocks",                      :default => 0,     :null => false
    t.integer  "count",                       :default => 0,     :null => false
    t.boolean  "cache_valid",                 :default => false, :null => false
  end

  add_index "directories", ["server_id"], :name => "directories_server_id"
  add_index "directories", ["level"], :name => "index_directories_on_level"
  add_index "directories", ["lft"], :name => "index_directories_on_lft"
  add_index "directories", ["server_id", "path"], :name => "index_directories_on_path_and_server_id", :unique => true
  add_index "directories", ["rgt"], :name => "index_directories_on_rgt"

  create_table "file_metadata_strings", :id => false, :force => true do |t|
    t.integer "file_id",            :null => false
    t.integer "metadata_string_id"
  end

  create_table "files", :force => true do |t|
    t.string   "name"
    t.datetime "modified"
    t.integer  "bytes"
    t.integer  "uid"
    t.integer  "gid"
    t.integer  "directory_id",                :null => false
    t.integer  "blocks",       :default => 0, :null => false
  end

  add_index "files", ["name"], :name => "files_name_idx"
  add_index "files", ["directory_id"], :name => "index_file_info_on_directory_id"

  create_table "metadata_attributes", :force => true do |t|
    t.string  "name",                 :null => false
    t.integer "plugin_descriptor_id", :null => false
  end

  add_index "metadata_attributes", ["name", "plugin_descriptor_id"], :name => "metadata_attributes_name_plugin_id_revision", :unique => true

  create_table "metadata_strings", :force => true do |t|
    t.integer "metadata_attribute_id", :null => false
    t.string  "value",                 :null => false
  end

  create_table "plugin_descriptors", :force => true do |t|
    t.string  "name",           :limit => 64, :null => false
    t.integer "version",                      :null => false
    t.binary  "code",                         :null => false
    t.binary  "sha1_signature",               :null => false
  end

  add_index "plugin_descriptors", ["name"], :name => "plugin_descriptors_unique_name", :unique => true

  create_table "servers", :force => true do |t|
    t.string   "name",                                                    :null => false
    t.integer  "heartbeat_interval",                     :default => 300, :null => false
    t.datetime "heartbeat_time"
    t.integer  "update_interval",                        :default => 300, :null => false
    t.datetime "last_update_finish_time"
    t.string   "daemon_version",          :limit => 128
  end

  add_index "servers", ["name"], :name => "index_servers_on_name", :unique => true

  add_foreign_key "directories", ["server_id"], "servers", ["id"], :on_delete => :cascade, :name => "directories_servers_id_fk"

  add_foreign_key "file_metadata_strings", ["file_id"], "files", ["id"], :on_delete => :cascade, :name => "file_metadata_file_id_fk"
  add_foreign_key "file_metadata_strings", ["metadata_string_id"], "metadata_strings", ["id"], :on_delete => :cascade, :name => "file_metadata_string_id_fk"

  add_foreign_key "files", ["directory_id"], "directories", ["id"], :on_delete => :cascade, :name => "files_directories_id_fk"

  add_foreign_key "metadata_attributes", ["plugin_descriptor_id"], "plugin_descriptors", ["id"], :on_delete => :cascade, :name => "metadata_attribute_plugin_descriptor_id_fk"

  add_foreign_key "metadata_strings", ["metadata_attribute_id"], "metadata_attributes", ["id"], :on_delete => :cascade, :name => "metadata_string_attribute_id_fk"

end
